// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_gIo1oSyIZoUmoI9OcYuvQ6UUuD5gQyk',
    appId: '1:770803828821:web:f4cc172fe5d30c38ceacdc',
    messagingSenderId: '770803828821',
    projectId: 'sos-app-54503',
    authDomain: 'sos-app-54503.firebaseapp.com',
    storageBucket: 'sos-app-54503.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQGW0T1M7T_egHM6pL51Lmkmcofn8IPUo',
    appId: '1:282826622893:android:c77bc2cf0eef5196a34324',
    messagingSenderId: '282826622893',
    projectId: 'emergency-system-aef7e',
    storageBucket: 'emergency-system-aef7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOC5o2ZZgv9aVLl77uNsy38dhBWTrk6Vk',
    appId: '1:770803828821:ios:cf612c60864c2defceacdc',
    messagingSenderId: '770803828821',
    projectId: 'sos-app-54503',
    storageBucket: 'sos-app-54503.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOC5o2ZZgv9aVLl77uNsy38dhBWTrk6Vk',
    appId: '1:770803828821:ios:cf612c60864c2defceacdc',
    messagingSenderId: '770803828821',
    projectId: 'sos-app-54503',
    storageBucket: 'sos-app-54503.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_gIo1oSyIZoUmoI9OcYuvQ6UUuD5gQyk',
    appId: '1:770803828821:web:f5fe1e792b89dc79ceacdc',
    messagingSenderId: '770803828821',
    projectId: 'sos-app-54503',
    authDomain: 'sos-app-54503.firebaseapp.com',
    storageBucket: 'sos-app-54503.firebasestorage.app',
  );
}